from typing import Generic, Protocol, Self, Type, TypeVar


T = TypeVar('T')


class UnitOfWorkProtocol(Protocol, Generic[T]):
    def __init__(self: Self, repository: Type[T]) -> None: ...
    
    async def __aenter__(self: Self): ...
    async def __aexit__(self: Self, *args): ...
    async def commit(self: Self): ...
    async def rollback(self: Self): ...